site_name: FitLife Documentation
theme: readthedocs
markdown_extensions:
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml
plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

nav:
  - Home: index.md
  - Architecture:
    - Context Diagram: architecture/context.md
    - Container Diagram: architecture/container.md
    - Component Diagram: architecture/component.md
    - Code Diagram: architecture/code.md